services:
  tooter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POETRY_VERSION: 1.5.1
    environment:
      MASTODON_OAUTH_TOKEN: /run/secrets/token
      TOOTS_DIR: /app/toots
    # volumes:
    #   - ./toots:/app/toots
    secrets:
      - token
secrets:
  token:
    file: token.txt